---
title: "Huilan(Claire) Tang"
---



### MD., MPH Candidate 2018, Columbia University Mailman School of Public Health



I received my MD degree from [University of South China](http://english.usc.edu.cn/) in 2016 and I'm pursuing the MPH in Epidemiology from [Columbia University Mailman School of Public Health](https://www.mailman.columbia.edu/).At the Mailman School, I focused on epidemiological study design and data analysis. My last internship was in [NewYork presbyterian hospital](http://www.nyp.org/),where I was responsible for the data analysis of MoSAIC study. Now I'm working as the data analysis intern (HRTP Program) at Bureau of Epidemiology Serivce of [NYC Department Health and Mental Hygiene](http://www1.nyc.gov/site/doh/index.page).

<br>

#### Academic and Professional Experience

My full resume is available [here](Downloads/Huilan(Claire)Tang resume.pdf).

<br>

#### Contact Information

Huilan Tang 


[Department of Epidemiology](https://www.mailman.columbia.edu/become-student/departments/epidemiology)  
[Columbia Mailman School of Public Health](http://www.mailman.columbia.edu/)  
722 West 168th Street 
New York, New York 10032  
Email: [ht2448@columbia.edu](mailto:ht2448@columbia.edu)  
Phone: (929)213-9868 




